### ISSUE TITLE
Key validation failed

### ISSUE THREAD

**Issue by null1024-ws** [DeepBitsTechnology/DeepDi#7]
Hi. I followed your instructions and start up the docker successfully. But when I ran "python3 DeepDi.py --key the_key_I_got_from_your_website --path ./test_data", an error "Key validation failed" occured. Is it something wrong with my operations? How to fix it? Thanks!

**Comment by Nifury** [comment]
Hello! Thank you for your interest in DeepDi. Could you check if your local date and time are correctly set and the access to https://data.mongodb-api.com is not blocked?

**Comment by null1024-ws** [comment]
Thanks for your quick response. I have checked my local date and time. It seemed that there was something wrong with the access to https://data.mongodb-api.com/ . How to fix this? I tried to shutdown the firewall, but it didn't work.

**Comment by Nifury** [comment]
Your ISP might be blocking the traffic to mongodb-api.com, which can be fixed by connecting through a VPN. 
If that doesn't work, could you email me (sheng@deepbits.com) your key so that we can further discuss this issue?
