### ISSUE TITLE
About Function Entrypoint Recovery

### ISSUE THREAD

**Issue by peicwang** [DeepBitsTechnology/DeepDi#8]
Hello, I noticed in your paper that in the function entry point recovery experiment, you first identified a set of entry point candidates. I would like to ask if this filtering of candidate sets is performed during both model training and testing when training function recovery models. Does the training set also perform similar candidate set filtering operations? I'am Looking forward to your reply！

**Comment by Nifury** [comment]
Hello,

Yes the model is trained on the filtered set.

**Comment by peicwang** [comment]
Thank you for your reply
